package corba8;
/**
* Mensagem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Receptor.idl
* Saturday, September 17, 2011 4:12:19 AM BRT
*/

public final class Mensagem implements org.omg.CORBA.portable.IDLEntity
{
  public String tipoMensagem = null;
  public int contador = (int)0;
  public int id = (int)0;
  public String mensagem = null;

  public Mensagem ()
  {
  } // ctor

  public Mensagem (String _tipoMensagem, int _contador, int _id, String _mensagem)
  {
    tipoMensagem = _tipoMensagem;
    contador = _contador;
    id = _id;
    mensagem = _mensagem;
  } // ctor

} // class Mensagem
