package corba8;
/**
* ReceptorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Receptor.idl
* Saturday, September 17, 2011 4:12:19 AM BRT
*/

public abstract class ReceptorPOA extends org.omg.PortableServer.Servant
 implements ReceptorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("enviaMensagem", new java.lang.Integer (0));
    _methods.put ("prontoParaEntrega", new java.lang.Integer (1));
    _methods.put ("mostraBuffer", new java.lang.Integer (2));
    _methods.put ("retornaID", new java.lang.Integer (3));
    _methods.put ("recebeuMensagemComConteudo", new java.lang.Integer (4));
    _methods.put ("podeDesalocar", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Receptor/enviaMensagem
       {
         Mensagem msg = MensagemHelper.read (in);
         this.enviaMensagem (msg);
         out = $rh.createReply();
         break;
       }

       case 1:  // Receptor/prontoParaEntrega
       {
         boolean $result = false;
         $result = this.prontoParaEntrega ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Receptor/mostraBuffer
       {
         this.mostraBuffer ();
         out = $rh.createReply();
         break;
       }

       case 3:  // Receptor/retornaID
       {
         int $result = (int)0;
         $result = this.retornaID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // Receptor/recebeuMensagemComConteudo
       {
         String conteudo = in.read_string ();
         boolean $result = false;
         $result = this.recebeuMensagemComConteudo (conteudo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // Receptor/podeDesalocar
       {
         boolean $result = false;
         $result = this.podeDesalocar ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Receptor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Receptor _this() 
  {
    return ReceptorHelper.narrow(
    super._this_object());
  }

  public Receptor _this(org.omg.CORBA.ORB orb) 
  {
    return ReceptorHelper.narrow(
    super._this_object(orb));
  }


} // class ReceptorPOA
