package corba8;
/**
* ReceptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Receptor.idl
* Saturday, September 17, 2011 4:12:19 AM BRT
*/

public final class ReceptorHolder implements org.omg.CORBA.portable.Streamable
{
  public Receptor value = null;

  public ReceptorHolder ()
  {
  }

  public ReceptorHolder (Receptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReceptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReceptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReceptorHelper.type ();
  }

}
